apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: techtrends
  name: techtrends
  namespace: {{ .Values.namespace.name }}
spec:
  replicas: {{ .Values.replicaCounts }}
  selector:
    matchLabels:
      app: techtrends
  template:
    metadata:
      labels:
        app: techtrends
    spec:
      containers:
      - name: techtrends
        image: registry.hub.docker.com/gampie/{{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        resources:
          requests:
            memory: {{ .Values.resources.requests.memory }}
            cpu: {{ .Values.resources.requests.cpu }}
          limits:
            memory: {{ .Values.resources.limits.memory }}
            cpu: {{ .Values.resources.limits.cpu }}
        ports:
        - containerPort: {{ .Values.containerPort }} 
        
        livenessProbe:
          httpGet:
            path: {{ .Values.probes.livenessProbe.path }}
            port: {{ .Values.containerPort }}
          failureThreshold: 1
          timeoutSeconds: 2
          initialDelaySeconds: 15
          periodSeconds: 15

        readinessProbe:
          httpGet:
            path: {{ .Values.probes.readinessProbe.path }}
            port: {{ .Values.containerPort }}
          failureThreshold: 2
          timeoutSeconds: 2
          initialDelaySeconds: 15
          periodSeconds: 5
