apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: techtrends
  name: techtrends
  namespace: sandbox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: techtrends
  template:
    metadata:
      labels:
        app: techtrends
    spec:
      containers:
      - name: techtrends
        image: registry.hub.docker.com/gampie/techtrends:latest
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3111
        
        livenessProbe:
          httpGet:
            path: /healthz
            port: 3111
          failureThreshold: 1
          timeoutSeconds: 2
          initialDelaySeconds: 15
          periodSeconds: 15

        readinessProbe:
          httpGet:
            path: /healthz
            port: 3111
          failureThreshold: 2
          timeoutSeconds: 2
          initialDelaySeconds: 15
          periodSeconds: 5
