apiVersion: v1
kind: Service
metadata:
  labels:
    app: techtrends
  name: techtrends
  namespace: sandbox
spec:
  selector:
    app: techtrends
  type: ClusterIP
  ports:
  - name: techtrends
    protocol: TCP
    port: 4111
    targetPort: 3111
